/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OnboardingState = IDL.Record({ 'isComplete' : IDL.Bool });
export const Recommendation = IDL.Record({
  'neighbourhood' : IDL.Text,
  'score' : IDL.Nat,
});
export const Time = IDL.Int;
export const ShortlistItem = IDL.Record({
  'savedAt' : Time,
  'neighbourhoodId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearShortlist' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOnboardingState' : IDL.Func([], [OnboardingState], ['query']),
  'getRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], ['query']),
  'getShortlistedNeighbourhoods' : IDL.Func(
      [],
      [IDL.Vec(ShortlistItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromShortlist' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePreferences' : IDL.Func([IDL.Text], [], []),
  'shortlistNeighbourhood' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OnboardingState = IDL.Record({ 'isComplete' : IDL.Bool });
  const Recommendation = IDL.Record({
    'neighbourhood' : IDL.Text,
    'score' : IDL.Nat,
  });
  const Time = IDL.Int;
  const ShortlistItem = IDL.Record({
    'savedAt' : Time,
    'neighbourhoodId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearShortlist' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOnboardingState' : IDL.Func([], [OnboardingState], ['query']),
    'getRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], ['query']),
    'getShortlistedNeighbourhoods' : IDL.Func(
        [],
        [IDL.Vec(ShortlistItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromShortlist' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePreferences' : IDL.Func([IDL.Text], [], []),
    'shortlistNeighbourhood' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };