/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OnboardingState { 'isComplete' : boolean }
export interface PulsePost {
  'id' : bigint,
  'postType' : string,
  'title' : string,
  'postedBy' : Principal,
  'createdAt' : Time,
  'description' : string,
  'neighbourhood' : string,
  'category' : string,
  'eventDate' : [] | [string],
}
export interface PulsePostInput {
  'postType' : string,
  'title' : string,
  'description' : string,
  'neighbourhood' : string,
  'category' : string,
  'eventDate' : [] | [string],
}
export interface Recommendation { 'neighbourhood' : string, 'score' : bigint }
export interface ShortlistItem { 'savedAt' : Time, 'neighbourhoodId' : bigint }
export interface SpaceListing {
  'id' : bigint,
  'title' : string,
  'postedBy' : Principal,
  'createdAt' : Time,
  'description' : string,
  'neighbourhood' : string,
  'spaceType' : string,
  'price' : bigint,
}
export interface SpaceListingInput {
  'title' : string,
  'description' : string,
  'neighbourhood' : string,
  'spaceType' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearShortlist' : ActorMethod<[], undefined>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'deletePulse' : ActorMethod<[bigint], undefined>,
  'getAllListings' : ActorMethod<[], Array<SpaceListing>>,
  'getAllPulses' : ActorMethod<[], Array<PulsePost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListingsByNeighbourhood' : ActorMethod<[string], Array<SpaceListing>>,
  'getOnboardingState' : ActorMethod<[], OnboardingState>,
  'getPulsesByNeighbourhood' : ActorMethod<[string], Array<PulsePost>>,
  'getRecommendations' : ActorMethod<[], Array<Recommendation>>,
  'getShortlistedNeighbourhoods' : ActorMethod<[], Array<ShortlistItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postPulse' : ActorMethod<[PulsePostInput], bigint>,
  'postSpaceListing' : ActorMethod<[SpaceListingInput], bigint>,
  'removeFromShortlist' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePreferences' : ActorMethod<[string], undefined>,
  'shortlistNeighbourhood' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];